apiVersion: apps/v1
kind: Deployment
metadata:
  name: autos-david
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autos-david
  template:
    metadata:
      labels:
        app: autos-david
    spec:
      containers:
        - image: $IMAGE
          name: autos-david
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-david
                  key: db_host
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db_david
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db_david
                  key: db_user
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: db_david
                  key: db_pwd
#            - name: DB_USER
#              value:
#            - name: DB_PWD
#              value:
      imagePullSecrets: # Be sure the token name matches what you created on K8s
        - name: k8s-token